#!/usr/bin/env bash
# Install nginx

apt-get update
apt-get install -y nginx

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World" > /var/www/html/index.html
service nginx restart
