#!/usr/bin/env bash
# Install nginx

apt-get update
apt-get install -y nginx

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
sed -i '/server_name _/a location /redirect_me { rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlw\u4? permanent; }' /etc/nginx/sites-available/default
sed -i '/server_name _/a error_page 404 /404.html; location = /404.html {root /var/www/html/; internal; }' /etc/nginx/sites-available/default
service nginx restart
